apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demodep
  name: demodep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demodep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demodep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
